; Cries indexes (see audio/cry_pointers.asm)
	const_def

; gen 1
	const CRY_NIDORAN_M
	const CRY_NIDORAN_F
	const CRY_SLOWPOKE
	const CRY_KANGASKHAN
	const CRY_CHARMANDER
	const CRY_GRIMER
	const CRY_VOLTORB
	const CRY_MUK
	const CRY_ODDISH
	const CRY_RAICHU
	const CRY_NIDOQUEEN
	const CRY_DIGLETT
	const CRY_SEEL
	const CRY_DROWZEE
	const CRY_PIDGEY
	const CRY_BULBIZARRE
	const CRY_SPEAROW
	const CRY_RHYDON
	const CRY_GOLEM
	const CRY_BLASTOISE
	const CRY_PIDGEOTTO
	const CRY_ASPICOT
	const CRY_CHENIPAN
	const CRY_ABO
	const CRY_FEAROW
	const CRY_CLEFAIRY
	const CRY_VENONAT
	const CRY_LAPRAS
	const CRY_CHRYSACIER
	const CRY_CARAPUCE
	const CRY_PARAS
	const CRY_CANINOS
	const CRY_KRABBY
	const CRY_PSYDUCK
	const CRY_RATTATA
	const CRY_VILEPLUME
	const CRY_GOUPIX
	const CRY_BOUSTIFLOR

; gen 2
	const CRY_MARILL
	const CRY_SPINARAK
	const CRY_TOGEPI
	const CRY_GIRAFARIG
	const CRY_RAIKOU
	const CRY_MAREEP
	const CRY_TOGETIC
	const CRY_HOOTHOOT
	const CRY_FOUINETTE
	const CRY_SLOWKING
	const CRY_CYNDAQUIL
	const CRY_GERMIGNON
	const CRY_TOTODILE
	const CRY_GLIGAR
	const CRY_CLEFFA
	const CRY_SLUGMA
	const CRY_COXY
	const CRY_ENTEI
	const CRY_AXOLOTO
	const CRY_DEMANTA
	const CRY_TYPHLOSION
	const CRY_NATU
	const CRY_TEDDIURSA
	const CRY_SUNFLORA
	const CRY_AMPHAROS
	const CRY_MAGCARGO
	const CRY_PICHU
	const CRY_CAPUMAIN
	const CRY_DUNSPARCE
	const CRY_DONPHAN

DEF NUM_CRIES EQU const_value
