Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 3, Cries
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangourex
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Grotadmorv
	dba Cry_Mystherbe
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Otaria
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbizarre
	dba Cry_Spearow
	dba Cry_Rhydon
	dba Cry_Grolem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Aspicot
	dba Cry_Chenipan
	dba Cry_Abo
	dba Cry_Fearow
	dba Cry_Melofee
	dba Cry_Mimitoss
	dba Cry_Lokhlass
	dba Cry_Chrysacier
	dba Cry_Carapuce
	dba Cry_Paras
	dba Cry_Caninos
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Goupix
	dba Cry_Boustiflor
	dba Cry_Marill
	dba Cry_Mimigal
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Hoothoot
	dba Cry_Fouinette
	dba Cry_Slowking
	dba Cry_Hericendre
	dba Cry_Germignon
	dba Cry_Kaiminus
	dba Cry_Gligar
	dba Cry_Melo
	dba Cry_Limagma
	dba Cry_Coxy
	dba Cry_Entei
	dba Cry_Axoloto
	dba Cry_Demanta
	dba Cry_Typhlosion
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Heliatronc
	dba Cry_Pharamp
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Capumain
	dba Cry_Insolourdo
	dba Cry_Donphan
	assert_table_length NUM_CRIES
