AnimationPointers:
	table_width 2, AnimationPointers
	dw BulbizarreAnimation
	dw HerbizarreAnimation
	dw FlorizarreAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw DracaufeuAnimation
	dw CarapuceAnimation
	dw CarabaffeAnimation
	dw BlastoiseAnimation
	dw ChenipanAnimation
	dw ChrysacierAnimation
	dw ButterfreeAnimation
	dw AspicotAnimation
	dw CoconfortAnimation
	dw DardargnanAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw RattataAnimation
	dw RaticateAnimation
	dw SpearowAnimation
	dw FearowAnimation
	dw AboAnimation
	dw ArbokAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw SandshrewAnimation
	dw SandslashAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw GoupixAnimation
	dw FeunardAnimation
	dw JigglypuffAnimation
	dw GrodoudouAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw VenonatAnimation
	dw AeromiteAnimation
	dw DiglettAnimation
	dw DugtrioAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw PsyduckAnimation
	dw AkwakwakAnimation
	dw FerosingeAnimation
	dw ColossingeAnimation
	dw CaninosAnimation
	dw ArcaninAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw ChetiflorAnimation
	dw BoustiflorAnimation
	dw EmpiflorAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudeAnimation
	dw GravalanchAnimation
	dw GrolemAnimation
	dw PonytaAnimation
	dw GalopaAnimation
	dw SlowpokeAnimation
	dw FlagadossAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw CanartichoAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw SeelAnimation
	dw LamantineAnimation
	dw GrimerAnimation
	dw GrotadmorvAnimation
	dw KokiyasAnimation
	dw CrustabriAnimation
	dw FantominusAnimation
	dw HaunterAnimation
	dw EctoplasmaAnimation
	dw OnixAnimation
	dw DrowzeeAnimation
	dw HypnomadeAnimation
	dw KrabbyAnimation
	dw KrabbossAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw KickleeAnimation
	dw HitmonchanAnimation
	dw ExcelangueAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw LeveinardAnimation
	dw TangelaAnimation
	dw KangourexAnimation
	dw HypotrempeAnimation
	dw HypoceanAnimation
	dw GoldeenAnimation
	dw SeakingAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimeAnimation
	dw InsecateurAnimation
	dw LippoutouAnimation
	dw ElektekAnimation
	dw MagmarAnimation
	dw PinsirAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw LeviatorAnimation
	dw LokhlassAnimation
	dw DittoAnimation
	dw EvoliAnimation
	dw AqualiAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw AmonitaAnimation
	dw AmonistarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArtikodinAnimation
	dw ElecthorAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DracoAnimation
	dw DracolosseAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw GermignonAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw HericendreAnimation
	dw FeurissonAnimation
	dw TyphlosionAnimation
	dw KaiminusAnimation
	dw CrocrodilAnimation
	dw AligatueurAnimation
	dw FouinetteAnimation
	dw FouinarAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw CoxyAnimation
	dw CoxyclaqueAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw LainergieAnimation
	dw AmpharosAnimation
	dw JoliflorAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw GranivolAnimation
	dw FloravolAnimation
	dw CotovolAnimation
	dw CapumainAnimation
	dw SunkernAnimation
	dw HeliatroncAnimation
	dw YanmaAnimation
	dw AxolotoAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw CornebreAnimation
	dw SlowkingAnimation
	dw FeuforeveAnimation
	dw UnownAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForetressAnimation
	dw InsolourdoAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishAnimation
	dw CizayoxAnimation
	dw CaratrocAnimation
	dw HeracrossAnimation
	dw FarfuretAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw LimagmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw CochignonAnimation
	dw CorayonAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw CadoizoAnimation
	dw DemantaAnimation
	dw AirmureAnimation
	dw HoundourAnimation
	dw DemolosseAnimation
	dw HyporoiAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw CerfrousseAnimation
	dw SmeargleAnimation
	dw DebugantAnimation
	dw KapoeraAnimation
	dw LippoutiAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw EcremeuhAnimation
	dw LeuphorieAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw EmbrylexAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	assert_table_length NUM_POKEMON
