AnimationPointers:
	table_width 2
	dw BulbizarreAnimation
	dw HerbizarreAnimation
	dw FlorizarreAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw DracaufeuAnimation
	dw CarapuceAnimation
	dw CarabaffeAnimation
	dw BlastoiseAnimation
	dw ChenipanAnimation
	dw ChrysacierAnimation
	dw PapilusionAnimation
	dw AspicotAnimation
	dw CoconfortAnimation
	dw DardargnanAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw RattataAnimation
	dw RaticateAnimation
	dw PiafabecAnimation
	dw FearowAnimation
	dw AboAnimation
	dw ArbokAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw SandshrewAnimation
	dw SandslashAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw MelofeeAnimation
	dw MelodelfeAnimation
	dw GoupixAnimation
	dw FeunardAnimation
	dw JigglypuffAnimation
	dw GrodoudouAnimation
	dw NosferaptiAnimation
	dw NosferaltoAnimation
	dw MystherbeAnimation
	dw OrtideAnimation
	dw RafflesiaAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw MimitossAnimation
	dw AeromiteAnimation
	dw DiglettAnimation
	dw DugtrioAnimation
	dw MiaoussAnimation
	dw PersianAnimation
	dw PsykokwakAnimation
	dw AkwakwakAnimation
	dw FerosingeAnimation
	dw ColossingeAnimation
	dw CaninosAnimation
	dw ArcaninAnimation
	dw PtitardAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachocAnimation
	dw MachopeurAnimation
	dw MackogneurAnimation
	dw ChetiflorAnimation
	dw BoustiflorAnimation
	dw EmpiflorAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw RacaillouAnimation
	dw GravalanchAnimation
	dw GrolemAnimation
	dw PonytaAnimation
	dw GalopaAnimation
	dw SlowpokeAnimation
	dw FlagadossAnimation
	dw MagnetiAnimation
	dw MagnetonAnimation
	dw CanartichoAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw OtariaAnimation
	dw LamantineAnimation
	dw GrimerAnimation
	dw GrotadmorvAnimation
	dw KokiyasAnimation
	dw CrustabriAnimation
	dw FantominusAnimation
	dw HaunterAnimation
	dw EctoplasmaAnimation
	dw OnixAnimation
	dw DrowzeeAnimation
	dw HypnomadeAnimation
	dw KrabbyAnimation
	dw KrabbossAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw NoeunoeufAnimation
	dw NoadkokoAnimation
	dw OsselaitAnimation
	dw OssatueurAnimation
	dw KickleeAnimation
	dw HitmonchanAnimation
	dw ExcelangueAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw LeveinardAnimation
	dw TangelaAnimation
	dw KangourexAnimation
	dw HypotrempeAnimation
	dw HypoceanAnimation
	dw PoissireneAnimation
	dw PoissoroyAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MMimeAnimation
	dw InsecateurAnimation
	dw LippoutouAnimation
	dw ElektekAnimation
	dw MagmarAnimation
	dw PinsirAnimation
	dw TaurosAnimation
	dw MagicarpeAnimation
	dw LeviatorAnimation
	dw LokhlassAnimation
	dw MetamorphAnimation
	dw EvoliAnimation
	dw AqualiAnimation
	dw JolteonAnimation
	dw PyroliAnimation
	dw PorygonAnimation
	dw AmonitaAnimation
	dw AmonistarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw PteraAnimation
	dw SnorlaxAnimation
	dw ArtikodinAnimation
	dw ElecthorAnimation
	dw MoltresAnimation
	dw MinidracoAnimation
	dw DracoAnimation
	dw DracolosseAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw GermignonAnimation
	dw MacroniumAnimation
	dw MeganiumAnimation
	dw HericendreAnimation
	dw FeurissonAnimation
	dw TyphlosionAnimation
	dw KaiminusAnimation
	dw CrocrodilAnimation
	dw AligatueurAnimation
	dw FouinetteAnimation
	dw FouinarAnimation
	dw HoothootAnimation
	dw NoarfangAnimation
	dw CoxyAnimation
	dw CoxyclaqueAnimation
	dw MimigalAnimation
	dw MigalosAnimation
	dw NostenferAnimation
	dw LoupioAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw MeloAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw LainergieAnimation
	dw PharampAnimation
	dw JoliflorAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw GranivolAnimation
	dw FloravolAnimation
	dw CotovolAnimation
	dw CapumainAnimation
	dw SunkernAnimation
	dw HeliatroncAnimation
	dw YanmaAnimation
	dw AxolotoAnimation
	dw MaraisteAnimation
	dw MentaliAnimation
	dw NoctaliAnimation
	dw CornebreAnimation
	dw SlowkingAnimation
	dw FeuforeveAnimation
	dw UnownAnimation
	dw QulbutokeAnimation
	dw GirafarigAnimation
	dw PomdepikAnimation
	dw ForetressAnimation
	dw InsolourdoAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishAnimation
	dw CizayoxAnimation
	dw CaratrocAnimation
	dw HeracrossAnimation
	dw FarfuretAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw LimagmaAnimation
	dw MagcargoAnimation
	dw MarcacrinAnimation
	dw CochignonAnimation
	dw CorayonAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw CadoizoAnimation
	dw DemantaAnimation
	dw AirmureAnimation
	dw MalosseAnimation
	dw DemolosseAnimation
	dw HyporoiAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw CerfrousseAnimation
	dw QueuloriorAnimation
	dw DebugantAnimation
	dw KapoeraAnimation
	dw LippoutiAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw EcremeuhAnimation
	dw LeuphorieAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw EmbrylexAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	assert_table_length NUM_POKEMON
