BitmasksPointers:
	table_width 2, BitmasksPointers
	dw BulbizarreBitmasks
	dw HerbizarreBitmasks
	dw FlorizarreBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw DracaufeuBitmasks
	dw CarapuceBitmasks
	dw CarabaffeBitmasks
	dw BlastoiseBitmasks
	dw ChenipanBitmasks
	dw ChrysacierBitmasks
	dw PapilusionBitmasks
	dw AspicotBitmasks
	dw CoconfortBitmasks
	dw DardargnanBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw PiafabecBitmasks
	dw FearowBitmasks
	dw AboBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw MelofeeBitmasks
	dw MelodelfeBitmasks
	dw GoupixBitmasks
	dw FeunardBitmasks
	dw JigglypuffBitmasks
	dw GrodoudouBitmasks
	dw NosferaptiBitmasks
	dw NosferaltoBitmasks
	dw MystherbeBitmasks
	dw OrtideBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw MimitossBitmasks
	dw AeromiteBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MiaoussBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw AkwakwakBitmasks
	dw FerosingeBitmasks
	dw ColossingeBitmasks
	dw CaninosBitmasks
	dw ArcaninBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachocBitmasks
	dw MachopeurBitmasks
	dw MackogneurBitmasks
	dw ChetiflorBitmasks
	dw BoustiflorBitmasks
	dw EmpiflorBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravalanchBitmasks
	dw GrolemBitmasks
	dw PonytaBitmasks
	dw GalopaBitmasks
	dw SlowpokeBitmasks
	dw FlagadossBitmasks
	dw MagnetiBitmasks
	dw MagnetonBitmasks
	dw CanartichoBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw OtariaBitmasks
	dw LamantineBitmasks
	dw GrimerBitmasks
	dw GrotadmorvBitmasks
	dw KokiyasBitmasks
	dw CrustabriBitmasks
	dw FantominusBitmasks
	dw HaunterBitmasks
	dw EctoplasmaBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnomadeBitmasks
	dw KrabbyBitmasks
	dw KrabbossBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw NoeunoeufBitmasks
	dw NoadkokoBitmasks
	dw OsselaitBitmasks
	dw OssatueurBitmasks
	dw KickleeBitmasks
	dw HitmonchanBitmasks
	dw ExcelangueBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw LeveinardBitmasks
	dw TangelaBitmasks
	dw KangourexBitmasks
	dw HypotrempeBitmasks
	dw HypoceanBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MMimeBitmasks
	dw InsecateurBitmasks
	dw LippoutouBitmasks
	dw ElektekBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagicarpeBitmasks
	dw LeviatorBitmasks
	dw LokhlassBitmasks
	dw MetamorphBitmasks
	dw EvoliBitmasks
	dw AqualiBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw AmonitaBitmasks
	dw AmonistarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArtikodinBitmasks
	dw ElecthorBitmasks
	dw MoltresBitmasks
	dw MinidracoBitmasks
	dw DracoBitmasks
	dw DracolosseBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw GermignonBitmasks
	dw MacroniumBitmasks
	dw MeganiumBitmasks
	dw HericendreBitmasks
	dw FeurissonBitmasks
	dw TyphlosionBitmasks
	dw KaiminusBitmasks
	dw CrocrodilBitmasks
	dw AligatueurBitmasks
	dw FouinetteBitmasks
	dw FouinarBitmasks
	dw HoothootBitmasks
	dw NoarfangBitmasks
	dw CoxyBitmasks
	dw CoxyclaqueBitmasks
	dw MimigalBitmasks
	dw MigalosBitmasks
	dw NostenferBitmasks
	dw LoupioBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw MeloBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw LainergieBitmasks
	dw PharampBitmasks
	dw JoliflorBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw GranivolBitmasks
	dw FloravolBitmasks
	dw CotovolBitmasks
	dw CapumainBitmasks
	dw SunkernBitmasks
	dw HeliatroncBitmasks
	dw YanmaBitmasks
	dw AxolotoBitmasks
	dw MaraisteBitmasks
	dw MentaliBitmasks
	dw NoctaliBitmasks
	dw CornebreBitmasks
	dw SlowkingBitmasks
	dw FeuforeveBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForetressBitmasks
	dw InsolourdoBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw CizayoxBitmasks
	dw CaratrocBitmasks
	dw HeracrossBitmasks
	dw FarfuretBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw LimagmaBitmasks
	dw MagcargoBitmasks
	dw MarcacrinBitmasks
	dw CochignonBitmasks
	dw CorayonBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw CadoizoBitmasks
	dw DemantaBitmasks
	dw AirmureBitmasks
	dw MalosseBitmasks
	dw DemolosseBitmasks
	dw HyporoiBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw CerfrousseBitmasks
	dw SmeargleBitmasks
	dw DebugantBitmasks
	dw KapoeraBitmasks
	dw LippoutiBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw EcremeuhBitmasks
	dw LeuphorieBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw EmbrylexBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	assert_table_length NUM_POKEMON
