FramesPointers:
	table_width 2, FramesPointers
	dw BulbizarreFrames
	dw HerbizarreFrames
	dw FlorizarreFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw DracaufeuFrames
	dw CarapuceFrames
	dw CarabaffeFrames
	dw BlastoiseFrames
	dw ChenipanFrames
	dw ChrysacierFrames
	dw ButterfreeFrames
	dw AspicotFrames
	dw CoconfortFrames
	dw DardargnanFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw RattataFrames
	dw RaticateFrames
	dw SpearowFrames
	dw FearowFrames
	dw AboFrames
	dw ArbokFrames
	dw PikachuFrames
	dw RaichuFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw GoupixFrames
	dw FeunardFrames
	dw JigglypuffFrames
	dw GrodoudouFrames
	dw ZubatFrames
	dw GolbatFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw ParasFrames
	dw ParasectFrames
	dw VenonatFrames
	dw AeromiteFrames
	dw DiglettFrames
	dw DugtrioFrames
	dw MeowthFrames
	dw PersianFrames
	dw PsyduckFrames
	dw AkwakwakFrames
	dw FerosingeFrames
	dw ColossingeFrames
	dw CaninosFrames
	dw ArcaninFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw ChetiflorFrames
	dw BoustiflorFrames
	dw EmpiflorFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravalanchFrames
	dw GrolemFrames
	dw PonytaFrames
	dw GalopaFrames
	dw SlowpokeFrames
	dw FlagadossFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw CanartichoFrames
	dw DoduoFrames
	dw DodrioFrames
	dw SeelFrames
	dw DewgongFrames
	dw GrimerFrames
	dw GrotadmorvFrames
	dw ShellderFrames
	dw CrustabriFrames
	dw FantominusFrames
	dw HaunterFrames
	dw EctoplasmaFrames
	dw OnixFrames
	dw DrowzeeFrames
	dw HypnomadeFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw CuboneFrames
	dw MarowakFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw ExcelangueFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw ChanseyFrames
	dw TangelaFrames
	dw KangaskhanFrames
	dw HypotrempeFrames
	dw HypoceanFrames
	dw GoldeenFrames
	dw SeakingFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw InsecateurFrames
	dw JynxFrames
	dw ElektekFrames
	dw MagmarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw EvoliFrames
	dw AqualiFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw AmonitaFrames
	dw AmonistarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw ArtikodinFrames
	dw ElecthorFrames
	dw MoltresFrames
	dw DratiniFrames
	dw DracoFrames
	dw DracolosseFrames
	dw MewtwoFrames
	dw MewFrames
	dw GermignonFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw HericendreFrames
	dw FeurissonFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CrocrodilFrames
	dw AligatueurFrames
	dw FouinetteFrames
	dw FouinarFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw CoxyFrames
	dw CoxyclaqueFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw PichuFrames
	dw CleffaFrames
	dw IgglybuffFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw GranivolFrames
	dw FloravolFrames
	dw CotovolFrames
	dw CapumainFrames
	dw SunkernFrames
	dw HeliatroncFrames
	dw YanmaFrames
	dw AxolotoFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw CornebreFrames
	dw SlowkingFrames
	dw FeuforeveFrames
	dw UnownFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForetressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw QwilfishFrames
	dw CizayoxFrames
	dw CaratrocFrames
	dw HeracrossFrames
	dw FarfuretFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw CochignonFrames
	dw CorayonFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw CadoizoFrames
	dw DemantaFrames
	dw AirmureFrames
	dw HoundourFrames
	dw DemolosseFrames
	dw HyporoiFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw Porygon2Frames
	dw CerfrousseFrames
	dw SmeargleFrames
	dw DebugantFrames
	dw HitmontopFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw EcremeuhFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw EmbrylexFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	assert_table_length NUM_POKEMON
