FramesPointers:
	table_width 2, FramesPointers
	dw BulbizarreFrames
	dw HerbizarreFrames
	dw FlorizarreFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw DracaufeuFrames
	dw CarapuceFrames
	dw CarabaffeFrames
	dw BlastoiseFrames
	dw ChenipanFrames
	dw ChrysacierFrames
	dw PapilusionFrames
	dw AspicotFrames
	dw CoconfortFrames
	dw DardargnanFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw RattataFrames
	dw RaticateFrames
	dw PiafabecFrames
	dw FearowFrames
	dw AboFrames
	dw ArbokFrames
	dw PikachuFrames
	dw RaichuFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw MelofeeFrames
	dw MelodelfeFrames
	dw GoupixFrames
	dw FeunardFrames
	dw JigglypuffFrames
	dw GrodoudouFrames
	dw NosferaptiFrames
	dw NosferaltoFrames
	dw MystherbeFrames
	dw OrtideFrames
	dw VileplumeFrames
	dw ParasFrames
	dw ParasectFrames
	dw MimitossFrames
	dw AeromiteFrames
	dw DiglettFrames
	dw DugtrioFrames
	dw MiaoussFrames
	dw PersianFrames
	dw PsyduckFrames
	dw AkwakwakFrames
	dw FerosingeFrames
	dw ColossingeFrames
	dw CaninosFrames
	dw ArcaninFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachocFrames
	dw MachopeurFrames
	dw MackogneurFrames
	dw ChetiflorFrames
	dw BoustiflorFrames
	dw EmpiflorFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravalanchFrames
	dw GrolemFrames
	dw PonytaFrames
	dw GalopaFrames
	dw SlowpokeFrames
	dw FlagadossFrames
	dw MagnetiFrames
	dw MagnetonFrames
	dw CanartichoFrames
	dw DoduoFrames
	dw DodrioFrames
	dw OtariaFrames
	dw LamantineFrames
	dw GrimerFrames
	dw GrotadmorvFrames
	dw KokiyasFrames
	dw CrustabriFrames
	dw FantominusFrames
	dw HaunterFrames
	dw EctoplasmaFrames
	dw OnixFrames
	dw DrowzeeFrames
	dw HypnomadeFrames
	dw KrabbyFrames
	dw KrabbossFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw NoeunoeufFrames
	dw NoadkokoFrames
	dw OsselaitFrames
	dw OssatueurFrames
	dw KickleeFrames
	dw HitmonchanFrames
	dw ExcelangueFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw LeveinardFrames
	dw TangelaFrames
	dw KangourexFrames
	dw HypotrempeFrames
	dw HypoceanFrames
	dw GoldeenFrames
	dw SeakingFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MMimeFrames
	dw InsecateurFrames
	dw LippoutouFrames
	dw ElektekFrames
	dw MagmarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MagicarpeFrames
	dw LeviatorFrames
	dw LokhlassFrames
	dw MetamorphFrames
	dw EvoliFrames
	dw AqualiFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw AmonitaFrames
	dw AmonistarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw ArtikodinFrames
	dw ElecthorFrames
	dw MoltresFrames
	dw MinidracoFrames
	dw DracoFrames
	dw DracolosseFrames
	dw MewtwoFrames
	dw MewFrames
	dw GermignonFrames
	dw MacroniumFrames
	dw MeganiumFrames
	dw HericendreFrames
	dw FeurissonFrames
	dw TyphlosionFrames
	dw KaiminusFrames
	dw CrocrodilFrames
	dw AligatueurFrames
	dw FouinetteFrames
	dw FouinarFrames
	dw HoothootFrames
	dw NoarfangFrames
	dw CoxyFrames
	dw CoxyclaqueFrames
	dw MimigalFrames
	dw MigalosFrames
	dw NostenferFrames
	dw LoupioFrames
	dw LanturnFrames
	dw PichuFrames
	dw MeloFrames
	dw IgglybuffFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw LainergieFrames
	dw PharampFrames
	dw JoliflorFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw GranivolFrames
	dw FloravolFrames
	dw CotovolFrames
	dw CapumainFrames
	dw SunkernFrames
	dw HeliatroncFrames
	dw YanmaFrames
	dw AxolotoFrames
	dw MaraisteFrames
	dw MentaliFrames
	dw NoctaliFrames
	dw CornebreFrames
	dw SlowkingFrames
	dw FeuforeveFrames
	dw UnownFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForetressFrames
	dw InsolourdoFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw QwilfishFrames
	dw CizayoxFrames
	dw CaratrocFrames
	dw HeracrossFrames
	dw FarfuretFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw LimagmaFrames
	dw MagcargoFrames
	dw MarcacrinFrames
	dw CochignonFrames
	dw CorayonFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw CadoizoFrames
	dw DemantaFrames
	dw AirmureFrames
	dw MalosseFrames
	dw DemolosseFrames
	dw HyporoiFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw Porygon2Frames
	dw CerfrousseFrames
	dw SmeargleFrames
	dw DebugantFrames
	dw KapoeraFrames
	dw LippoutiFrames
	dw ElekidFrames
	dw MagbyFrames
	dw EcremeuhFrames
	dw LeuphorieFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw EmbrylexFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	assert_table_length NUM_POKEMON
