AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw BulbizarreAnimationIdle
	dw HerbizarreAnimationIdle
	dw FlorizarreAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw DracaufeuAnimationIdle
	dw CarapuceAnimationIdle
	dw CarabaffeAnimationIdle
	dw BlastoiseAnimationIdle
	dw ChenipanAnimationIdle
	dw ChrysacierAnimationIdle
	dw ButterfreeAnimationIdle
	dw AspicotAnimationIdle
	dw CoconfortAnimationIdle
	dw DardargnanAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw RattataAnimationIdle
	dw RaticateAnimationIdle
	dw SpearowAnimationIdle
	dw FearowAnimationIdle
	dw AboAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw MelofeeAnimationIdle
	dw MelodelfeAnimationIdle
	dw GoupixAnimationIdle
	dw FeunardAnimationIdle
	dw JigglypuffAnimationIdle
	dw GrodoudouAnimationIdle
	dw NosferaptiAnimationIdle
	dw NosferaltoAnimationIdle
	dw MystherbeAnimationIdle
	dw OrtideAnimationIdle
	dw VileplumeAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw MimitossAnimationIdle
	dw AeromiteAnimationIdle
	dw DiglettAnimationIdle
	dw DugtrioAnimationIdle
	dw MiaoussAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw AkwakwakAnimationIdle
	dw FerosingeAnimationIdle
	dw ColossingeAnimationIdle
	dw CaninosAnimationIdle
	dw ArcaninAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachocAnimationIdle
	dw MachopeurAnimationIdle
	dw MackogneurAnimationIdle
	dw ChetiflorAnimationIdle
	dw BoustiflorAnimationIdle
	dw EmpiflorAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravalanchAnimationIdle
	dw GrolemAnimationIdle
	dw PonytaAnimationIdle
	dw GalopaAnimationIdle
	dw SlowpokeAnimationIdle
	dw FlagadossAnimationIdle
	dw MagnetiAnimationIdle
	dw MagnetonAnimationIdle
	dw CanartichoAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw LamantineAnimationIdle
	dw GrimerAnimationIdle
	dw GrotadmorvAnimationIdle
	dw KokiyasAnimationIdle
	dw CrustabriAnimationIdle
	dw FantominusAnimationIdle
	dw HaunterAnimationIdle
	dw EctoplasmaAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnomadeAnimationIdle
	dw KrabbyAnimationIdle
	dw KrabbossAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw NoeunoeufAnimationIdle
	dw NoadkokoAnimationIdle
	dw CuboneAnimationIdle
	dw OssatueurAnimationIdle
	dw KickleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw ExcelangueAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw LeveinardAnimationIdle
	dw TangelaAnimationIdle
	dw KangourexAnimationIdle
	dw HypotrempeAnimationIdle
	dw HypoceanAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MMimeAnimationIdle
	dw InsecateurAnimationIdle
	dw LippoutouAnimationIdle
	dw ElektekAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw MagicarpeAnimationIdle
	dw LeviatorAnimationIdle
	dw LokhlassAnimationIdle
	dw MetamorphAnimationIdle
	dw EvoliAnimationIdle
	dw AqualiAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw AmonitaAnimationIdle
	dw AmonistarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArtikodinAnimationIdle
	dw ElecthorAnimationIdle
	dw MoltresAnimationIdle
	dw MinidracoAnimationIdle
	dw DracoAnimationIdle
	dw DracolosseAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw GermignonAnimationIdle
	dw MacroniumAnimationIdle
	dw MeganiumAnimationIdle
	dw HericendreAnimationIdle
	dw FeurissonAnimationIdle
	dw TyphlosionAnimationIdle
	dw KaiminusAnimationIdle
	dw CrocrodilAnimationIdle
	dw AligatueurAnimationIdle
	dw FouinetteAnimationIdle
	dw FouinarAnimationIdle
	dw HoothootAnimationIdle
	dw NoarfangAnimationIdle
	dw CoxyAnimationIdle
	dw CoxyclaqueAnimationIdle
	dw MimigalAnimationIdle
	dw MigalosAnimationIdle
	dw NostenferAnimationIdle
	dw LoupioAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw MeloAnimationIdle
	dw IgglybuffAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw LainergieAnimationIdle
	dw AmpharosAnimationIdle
	dw JoliflorAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PolitoedAnimationIdle
	dw GranivolAnimationIdle
	dw FloravolAnimationIdle
	dw CotovolAnimationIdle
	dw CapumainAnimationIdle
	dw SunkernAnimationIdle
	dw HeliatroncAnimationIdle
	dw YanmaAnimationIdle
	dw AxolotoAnimationIdle
	dw MaraisteAnimationIdle
	dw MentaliAnimationIdle
	dw NoctaliAnimationIdle
	dw CornebreAnimationIdle
	dw SlowkingAnimationIdle
	dw FeuforeveAnimationIdle
	dw UnownAnimationIdle
	dw WobbuffetAnimationIdle
	dw GirafarigAnimationIdle
	dw PinecoAnimationIdle
	dw ForetressAnimationIdle
	dw InsolourdoAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw CizayoxAnimationIdle
	dw CaratrocAnimationIdle
	dw HeracrossAnimationIdle
	dw FarfuretAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw LimagmaAnimationIdle
	dw MagcargoAnimationIdle
	dw MarcacrinAnimationIdle
	dw CochignonAnimationIdle
	dw CorayonAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw CadoizoAnimationIdle
	dw DemantaAnimationIdle
	dw AirmureAnimationIdle
	dw MalosseAnimationIdle
	dw DemolosseAnimationIdle
	dw HyporoiAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw CerfrousseAnimationIdle
	dw SmeargleAnimationIdle
	dw DebugantAnimationIdle
	dw KapoeraAnimationIdle
	dw LippoutiAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw EcremeuhAnimationIdle
	dw LeuphorieAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw EmbrylexAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	assert_table_length NUM_POKEMON
