AnimationIdlePointers:
	table_width 2
	dw BulbizarreAnimationIdle
	dw HerbizarreAnimationIdle
	dw FlorizarreAnimationIdle
	dw SalamecheAnimationIdle
	dw ReptincelAnimationIdle
	dw DracaufeuAnimationIdle
	dw CarapuceAnimationIdle
	dw CarabaffeAnimationIdle
	dw TortankAnimationIdle
	dw ChenipanAnimationIdle
	dw ChrysacierAnimationIdle
	dw PapilusionAnimationIdle
	dw AspicotAnimationIdle
	dw CoconfortAnimationIdle
	dw DardargnanAnimationIdle
	dw RoucoolAnimationIdle
	dw RoucoupsAnimationIdle
	dw RoucarnageAnimationIdle
	dw RattataAnimationIdle
	dw RattatacAnimationIdle
	dw PiafabecAnimationIdle
	dw RapasdepicAnimationIdle
	dw AboAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SabeletteAnimationIdle
	dw SablaireauAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw MelofeeAnimationIdle
	dw MelodelfeAnimationIdle
	dw GoupixAnimationIdle
	dw FeunardAnimationIdle
	dw RondoudouAnimationIdle
	dw GrodoudouAnimationIdle
	dw NosferaptiAnimationIdle
	dw NosferaltoAnimationIdle
	dw MystherbeAnimationIdle
	dw OrtideAnimationIdle
	dw RafflesiaAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw MimitossAnimationIdle
	dw AeromiteAnimationIdle
	dw TaupiqueurAnimationIdle
	dw TriopikeurAnimationIdle
	dw MiaoussAnimationIdle
	dw PersianAnimationIdle
	dw PsykokwakAnimationIdle
	dw AkwakwakAnimationIdle
	dw FerosingeAnimationIdle
	dw ColossingeAnimationIdle
	dw CaninosAnimationIdle
	dw ArcaninAnimationIdle
	dw PtitardAnimationIdle
	dw TetarteAnimationIdle
	dw TartardAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachocAnimationIdle
	dw MachopeurAnimationIdle
	dw MackogneurAnimationIdle
	dw ChetiflorAnimationIdle
	dw BoustiflorAnimationIdle
	dw EmpiflorAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw RacaillouAnimationIdle
	dw GravalanchAnimationIdle
	dw GrolemAnimationIdle
	dw PonytaAnimationIdle
	dw GalopaAnimationIdle
	dw RamolossAnimationIdle
	dw FlagadossAnimationIdle
	dw MagnetiAnimationIdle
	dw MagnetonAnimationIdle
	dw CanartichoAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw OtariaAnimationIdle
	dw LamantineAnimationIdle
	dw TadmorvAnimationIdle
	dw GrotadmorvAnimationIdle
	dw KokiyasAnimationIdle
	dw CrustabriAnimationIdle
	dw FantominusAnimationIdle
	dw SpectrumAnimationIdle
	dw EctoplasmaAnimationIdle
	dw OnixAnimationIdle
	dw SoporifikAnimationIdle
	dw HypnomadeAnimationIdle
	dw KrabbyAnimationIdle
	dw KrabbossAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw NoeunoeufAnimationIdle
	dw NoadkokoAnimationIdle
	dw OsselaitAnimationIdle
	dw OssatueurAnimationIdle
	dw KickleeAnimationIdle
	dw TygnonAnimationIdle
	dw ExcelangueAnimationIdle
	dw SmogoAnimationIdle
	dw SmogogoAnimationIdle
	dw RhinocorneAnimationIdle
	dw RhinoferosAnimationIdle
	dw LeveinardAnimationIdle
	dw SaquedeneuAnimationIdle
	dw KangourexAnimationIdle
	dw HypotrempeAnimationIdle
	dw HypoceanAnimationIdle
	dw PoissireneAnimationIdle
	dw PoissoroyAnimationIdle
	dw StariAnimationIdle
	dw StarossAnimationIdle
	dw MMimeAnimationIdle
	dw InsecateurAnimationIdle
	dw LippoutouAnimationIdle
	dw ElektekAnimationIdle
	dw MagmarAnimationIdle
	dw ScarabruteAnimationIdle
	dw TaurosAnimationIdle
	dw MagicarpeAnimationIdle
	dw LeviatorAnimationIdle
	dw LokhlassAnimationIdle
	dw MetamorphAnimationIdle
	dw EvoliAnimationIdle
	dw AqualiAnimationIdle
	dw JolteonAnimationIdle
	dw PyroliAnimationIdle
	dw PorygonAnimationIdle
	dw AmonitaAnimationIdle
	dw AmonistarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw PteraAnimationIdle
	dw RonflexAnimationIdle
	dw ArtikodinAnimationIdle
	dw ElecthorAnimationIdle
	dw SulfuraAnimationIdle
	dw MinidracoAnimationIdle
	dw DracoAnimationIdle
	dw DracolosseAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw GermignonAnimationIdle
	dw MacroniumAnimationIdle
	dw MeganiumAnimationIdle
	dw HericendreAnimationIdle
	dw FeurissonAnimationIdle
	dw TyphlosionAnimationIdle
	dw KaiminusAnimationIdle
	dw CrocrodilAnimationIdle
	dw AligatueurAnimationIdle
	dw FouinetteAnimationIdle
	dw FouinarAnimationIdle
	dw HoothootAnimationIdle
	dw NoarfangAnimationIdle
	dw CoxyAnimationIdle
	dw CoxyclaqueAnimationIdle
	dw MimigalAnimationIdle
	dw MigalosAnimationIdle
	dw NostenferAnimationIdle
	dw LoupioAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw MeloAnimationIdle
	dw ToudoudouAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw LainergieAnimationIdle
	dw PharampAnimationIdle
	dw JoliflorAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SimularbreAnimationIdle
	dw TarpaudAnimationIdle
	dw GranivolAnimationIdle
	dw FloravolAnimationIdle
	dw CotovolAnimationIdle
	dw CapumainAnimationIdle
	dw TournegrinAnimationIdle
	dw HeliatroncAnimationIdle
	dw YanmaAnimationIdle
	dw AxolotoAnimationIdle
	dw MaraisteAnimationIdle
	dw MentaliAnimationIdle
	dw NoctaliAnimationIdle
	dw CornebreAnimationIdle
	dw RoigadaAnimationIdle
	dw FeuforeveAnimationIdle
	dw UnownAnimationIdle
	dw QulbutokeAnimationIdle
	dw GirafarigAnimationIdle
	dw PomdepikAnimationIdle
	dw ForetressAnimationIdle
	dw InsolourdoAnimationIdle
	dw ScorplaneAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw CizayoxAnimationIdle
	dw CaratrocAnimationIdle
	dw ScarhinoAnimationIdle
	dw FarfuretAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw LimagmaAnimationIdle
	dw MagcargoAnimationIdle
	dw MarcacrinAnimationIdle
	dw CochignonAnimationIdle
	dw CorayonAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw CadoizoAnimationIdle
	dw DemantaAnimationIdle
	dw AirmureAnimationIdle
	dw MalosseAnimationIdle
	dw DemolosseAnimationIdle
	dw HyporoiAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw CerfrousseAnimationIdle
	dw QueuloriorAnimationIdle
	dw DebugantAnimationIdle
	dw KapoeraAnimationIdle
	dw LippoutiAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw EcremeuhAnimationIdle
	dw LeuphorieAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw EmbrylexAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	assert_table_length NUM_POKEMON
