ZarbiAnimationIdlePointers:
	table_width 2
	dw ZarbiAAnimationIdle
	dw ZarbiBAnimationIdle
	dw ZarbiCAnimationIdle
	dw ZarbiDAnimationIdle
	dw ZarbiEAnimationIdle
	dw ZarbiFAnimationIdle
	dw ZarbiGAnimationIdle
	dw ZarbiHAnimationIdle
	dw ZarbiIAnimationIdle
	dw ZarbiJAnimationIdle
	dw ZarbiKAnimationIdle
	dw ZarbiLAnimationIdle
	dw ZarbiMAnimationIdle
	dw ZarbiNAnimationIdle
	dw ZarbiOAnimationIdle
	dw ZarbiPAnimationIdle
	dw ZarbiQAnimationIdle
	dw ZarbiRAnimationIdle
	dw ZarbiSAnimationIdle
	dw ZarbiTAnimationIdle
	dw ZarbiUAnimationIdle
	dw ZarbiVAnimationIdle
	dw ZarbiWAnimationIdle
	dw ZarbiXAnimationIdle
	dw ZarbiYAnimationIdle
	dw ZarbiZAnimationIdle
	assert_table_length NUM_ZARBI
