ZarbiFramesPointers:
	table_width 2
	dw ZarbiAFrames
	dw ZarbiBFrames
	dw ZarbiCFrames
	dw ZarbiDFrames
	dw ZarbiEFrames
	dw ZarbiFFrames
	dw ZarbiGFrames
	dw ZarbiHFrames
	dw ZarbiIFrames
	dw ZarbiJFrames
	dw ZarbiKFrames
	dw ZarbiLFrames
	dw ZarbiMFrames
	dw ZarbiNFrames
	dw ZarbiOFrames
	dw ZarbiPFrames
	dw ZarbiQFrames
	dw ZarbiRFrames
	dw ZarbiSFrames
	dw ZarbiTFrames
	dw ZarbiUFrames
	dw ZarbiVFrames
	dw ZarbiWFrames
	dw ZarbiXFrames
	dw ZarbiYFrames
	dw ZarbiZFrames
	assert_table_length NUM_ZARBI
