ZarbiBitmasksPointers:
	table_width 2
	dw ZarbiABitmasks
	dw ZarbiBBitmasks
	dw ZarbiCBitmasks
	dw ZarbiDBitmasks
	dw ZarbiEBitmasks
	dw ZarbiFBitmasks
	dw ZarbiGBitmasks
	dw ZarbiHBitmasks
	dw ZarbiIBitmasks
	dw ZarbiJBitmasks
	dw ZarbiKBitmasks
	dw ZarbiLBitmasks
	dw ZarbiMBitmasks
	dw ZarbiNBitmasks
	dw ZarbiOBitmasks
	dw ZarbiPBitmasks
	dw ZarbiQBitmasks
	dw ZarbiRBitmasks
	dw ZarbiSBitmasks
	dw ZarbiTBitmasks
	dw ZarbiUBitmasks
	dw ZarbiVBitmasks
	dw ZarbiWBitmasks
	dw ZarbiXBitmasks
	dw ZarbiYBitmasks
	dw ZarbiZBitmasks
	assert_table_length NUM_ZARBI
