ZarbiAnimationPointers:
	table_width 2
	dw ZarbiAAnimation
	dw ZarbiBAnimation
	dw ZarbiCAnimation
	dw ZarbiDAnimation
	dw ZarbiEAnimation
	dw ZarbiFAnimation
	dw ZarbiGAnimation
	dw ZarbiHAnimation
	dw ZarbiIAnimation
	dw ZarbiJAnimation
	dw ZarbiKAnimation
	dw ZarbiLAnimation
	dw ZarbiMAnimation
	dw ZarbiNAnimation
	dw ZarbiOAnimation
	dw ZarbiPAnimation
	dw ZarbiQAnimation
	dw ZarbiRAnimation
	dw ZarbiSAnimation
	dw ZarbiTAnimation
	dw ZarbiUAnimation
	dw ZarbiVAnimation
	dw ZarbiWAnimation
	dw ZarbiXAnimation
	dw ZarbiYAnimation
	dw ZarbiZAnimation
	assert_table_length NUM_ZARBI
