ZarbisFrames: ; used only for BANK(ZarbisFrames)

ZarbiAFrames: INCLUDE "gfx/pokemon/zarbi_a/frames.asm"
ZarbiBFrames: INCLUDE "gfx/pokemon/zarbi_b/frames.asm"
ZarbiCFrames: INCLUDE "gfx/pokemon/zarbi_c/frames.asm"
ZarbiDFrames: INCLUDE "gfx/pokemon/zarbi_d/frames.asm"
ZarbiEFrames: INCLUDE "gfx/pokemon/zarbi_e/frames.asm"
ZarbiFFrames: INCLUDE "gfx/pokemon/zarbi_f/frames.asm"
ZarbiGFrames: INCLUDE "gfx/pokemon/zarbi_g/frames.asm"
ZarbiHFrames: INCLUDE "gfx/pokemon/zarbi_h/frames.asm"
ZarbiIFrames: INCLUDE "gfx/pokemon/zarbi_i/frames.asm"
ZarbiJFrames: INCLUDE "gfx/pokemon/zarbi_j/frames.asm"
ZarbiKFrames: INCLUDE "gfx/pokemon/zarbi_k/frames.asm"
ZarbiLFrames: INCLUDE "gfx/pokemon/zarbi_l/frames.asm"
ZarbiMFrames: INCLUDE "gfx/pokemon/zarbi_m/frames.asm"
ZarbiNFrames: INCLUDE "gfx/pokemon/zarbi_n/frames.asm"
ZarbiOFrames: INCLUDE "gfx/pokemon/zarbi_o/frames.asm"
ZarbiPFrames: INCLUDE "gfx/pokemon/zarbi_p/frames.asm"
ZarbiQFrames: INCLUDE "gfx/pokemon/zarbi_q/frames.asm"
ZarbiRFrames: INCLUDE "gfx/pokemon/zarbi_r/frames.asm"
ZarbiSFrames: INCLUDE "gfx/pokemon/zarbi_s/frames.asm"
ZarbiTFrames: INCLUDE "gfx/pokemon/zarbi_t/frames.asm"
ZarbiUFrames: INCLUDE "gfx/pokemon/zarbi_u/frames.asm"
ZarbiVFrames: INCLUDE "gfx/pokemon/zarbi_v/frames.asm"
ZarbiWFrames: INCLUDE "gfx/pokemon/zarbi_w/frames.asm"
ZarbiXFrames: INCLUDE "gfx/pokemon/zarbi_x/frames.asm"
ZarbiYFrames: INCLUDE "gfx/pokemon/zarbi_y/frames.asm"
ZarbiZFrames: INCLUDE "gfx/pokemon/zarbi_z/frames.asm"
