; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in layout.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

HoOhFrontpic:        INCBIN "gfx/pokemon/ho_oh/front.animated.2bpp.lz"
MackogneurFrontpic:     INCBIN "gfx/pokemon/mackogneur/front.animated.2bpp.lz"
FeunardFrontpic:   INCBIN "gfx/pokemon/feunard/front.animated.2bpp.lz"
AligatueurFrontpic:  INCBIN "gfx/pokemon/aligatueur/front.animated.2bpp.lz"
NidokingFrontpic:    INCBIN "gfx/pokemon/nidoking/front.animated.2bpp.lz"
RaikouFrontpic:      INCBIN "gfx/pokemon/raikou/front.animated.2bpp.lz"
LugiaFrontpic:       INCBIN "gfx/pokemon/lugia/front.animated.2bpp.lz"
ArtikodinFrontpic:    INCBIN "gfx/pokemon/artikodin/front.animated.2bpp.lz"
TaurosFrontpic:      INCBIN "gfx/pokemon/tauros/front.animated.2bpp.lz"
FlorizarreFrontpic:    INCBIN "gfx/pokemon/florizarre/front.animated.2bpp.lz"
EnteiFrontpic:       INCBIN "gfx/pokemon/entei/front.animated.2bpp.lz"
SuicuneFrontpic:     INCBIN "gfx/pokemon/suicune/front.animated.2bpp.lz"
TyphlosionFrontpic:  INCBIN "gfx/pokemon/typhlosion/front.animated.2bpp.lz"


SECTION "Pics 2", ROMX

BlastoiseFrontpic:   INCBIN "gfx/pokemon/blastoise/front.animated.2bpp.lz"
GalopaFrontpic:    INCBIN "gfx/pokemon/galopa/front.animated.2bpp.lz"
MeganiumFrontpic:    INCBIN "gfx/pokemon/meganium/front.animated.2bpp.lz"
NidoqueenFrontpic:   INCBIN "gfx/pokemon/nidoqueen/front.animated.2bpp.lz"
KickleeFrontpic:   INCBIN "gfx/pokemon/kicklee/front.animated.2bpp.lz"
CizayoxFrontpic:      INCBIN "gfx/pokemon/cizayox/front.animated.2bpp.lz"
DardargnanFrontpic:    INCBIN "gfx/pokemon/dardargnan/front.animated.2bpp.lz"
ArcaninFrontpic:    INCBIN "gfx/pokemon/arcanin/front.animated.2bpp.lz"
TyranitarFrontpic:   INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
MoltresFrontpic:     INCBIN "gfx/pokemon/moltres/front.animated.2bpp.lz"
ElecthorFrontpic:      INCBIN "gfx/pokemon/electhor/front.animated.2bpp.lz"
ArbokFrontpic:       INCBIN "gfx/pokemon/arbok/front.animated.2bpp.lz"
MewtwoFrontpic:      INCBIN "gfx/pokemon/mewtwo/front.animated.2bpp.lz"
FearowFrontpic:      INCBIN "gfx/pokemon/fearow/front.animated.2bpp.lz"
DracaufeuFrontpic:   INCBIN "gfx/pokemon/dracaufeu/front.animated.2bpp.lz"
FeurissonFrontpic:     INCBIN "gfx/pokemon/feurisson/front.animated.2bpp.lz"


SECTION "Pics 3", ROMX

SteelixFrontpic:     INCBIN "gfx/pokemon/steelix/front.animated.2bpp.lz"
AlakazamFrontpic:    INCBIN "gfx/pokemon/alakazam/front.animated.2bpp.lz"
LeviatorFrontpic:    INCBIN "gfx/pokemon/leviator/front.animated.2bpp.lz"
KangourexFrontpic:  INCBIN "gfx/pokemon/kangourex/front.animated.2bpp.lz"
RhydonFrontpic:      INCBIN "gfx/pokemon/rhydon/front.animated.2bpp.lz"
AkwakwakFrontpic:     INCBIN "gfx/pokemon/akwakwak/front.animated.2bpp.lz"
RhyhornFrontpic:     INCBIN "gfx/pokemon/rhyhorn/front.animated.2bpp.lz"
PidgeotFrontpic:     INCBIN "gfx/pokemon/pidgeot/front.animated.2bpp.lz"
FlagadossFrontpic:     INCBIN "gfx/pokemon/flagadoss/front.animated.2bpp.lz"
ButterfreeFrontpic:  INCBIN "gfx/pokemon/butterfree/front.animated.2bpp.lz"
WeezingFrontpic:     INCBIN "gfx/pokemon/weezing/front.animated.2bpp.lz"
CrustabriFrontpic:    INCBIN "gfx/pokemon/crustabri/front.animated.2bpp.lz"
AirmureFrontpic:    INCBIN "gfx/pokemon/airmure/front.animated.2bpp.lz"
LamantineFrontpic:     INCBIN "gfx/pokemon/lamantine/front.animated.2bpp.lz"
EmpiflorFrontpic:  INCBIN "gfx/pokemon/empiflor/front.animated.2bpp.lz"
RaichuFrontpic:      INCBIN "gfx/pokemon/raichu/front.animated.2bpp.lz"
ColossingeFrontpic:    INCBIN "gfx/pokemon/colossinge/front.animated.2bpp.lz"
AmonistarBackpic:      INCBIN "gfx/pokemon/amonistar/back.2bpp.lz"


SECTION "Pics 4", ROMX

DodrioFrontpic:      INCBIN "gfx/pokemon/dodrio/front.animated.2bpp.lz"
SlowkingFrontpic:    INCBIN "gfx/pokemon/slowking/front.animated.2bpp.lz"
KapoeraFrontpic:   INCBIN "gfx/pokemon/kapoera/front.animated.2bpp.lz"
OnixFrontpic:        INCBIN "gfx/pokemon/onix/front.animated.2bpp.lz"
LeuphorieFrontpic:     INCBIN "gfx/pokemon/leuphorie/front.animated.2bpp.lz"
MachopeurFrontpic:     INCBIN "gfx/pokemon/machopeur/front.animated.2bpp.lz"
DracolosseFrontpic:   INCBIN "gfx/pokemon/dracolosse/front.animated.2bpp.lz"
PoliwrathFrontpic:   INCBIN "gfx/pokemon/poliwrath/front.animated.2bpp.lz"
InsecateurFrontpic:     INCBIN "gfx/pokemon/insecateur/front.animated.2bpp.lz"
AerodactylFrontpic:  INCBIN "gfx/pokemon/aerodactyl/front.animated.2bpp.lz"
SeakingFrontpic:     INCBIN "gfx/pokemon/seaking/front.animated.2bpp.lz"
GrotadmorvFrontpic:         INCBIN "gfx/pokemon/grotadmorv/front.animated.2bpp.lz"
CrocrodilFrontpic:    INCBIN "gfx/pokemon/crocrodil/front.animated.2bpp.lz"
HypnomadeFrontpic:       INCBIN "gfx/pokemon/hypnomade/front.animated.2bpp.lz"
NidorinoFrontpic:    INCBIN "gfx/pokemon/nidorino/front.animated.2bpp.lz"
SandslashFrontpic:   INCBIN "gfx/pokemon/sandslash/front.animated.2bpp.lz"
JolteonFrontpic:     INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
DonphanFrontpic:     INCBIN "gfx/pokemon/donphan/front.animated.2bpp.lz"
PinsirFrontpic:      INCBIN "gfx/pokemon/pinsir/front.animated.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"


SECTION "Pics 5", ROMX

GolbatFrontpic:      INCBIN "gfx/pokemon/golbat/front.animated.2bpp.lz"
KrabbossFrontpic:     INCBIN "gfx/pokemon/krabboss/front.animated.2bpp.lz"
ExeggcuteFrontpic:   INCBIN "gfx/pokemon/exeggcute/front.animated.2bpp.lz"
MagcargoFrontpic:    INCBIN "gfx/pokemon/magcargo/front.animated.2bpp.lz"
PersianFrontpic:     INCBIN "gfx/pokemon/persian/front.animated.2bpp.lz"
CerfrousseFrontpic:    INCBIN "gfx/pokemon/cerfrousse/front.animated.2bpp.lz"
RaticateFrontpic:    INCBIN "gfx/pokemon/raticate/front.animated.2bpp.lz"
AeromiteFrontpic:    INCBIN "gfx/pokemon/aeromite/front.animated.2bpp.lz"
PolitoedFrontpic:    INCBIN "gfx/pokemon/politoed/front.animated.2bpp.lz"
ElektekFrontpic:  INCBIN "gfx/pokemon/elektek/front.animated.2bpp.lz"
DemantaFrontpic:     INCBIN "gfx/pokemon/demanta/front.animated.2bpp.lz"
ExcelangueFrontpic:   INCBIN "gfx/pokemon/excelangue/front.animated.2bpp.lz"
HyporoiFrontpic:     INCBIN "gfx/pokemon/hyporoi/front.animated.2bpp.lz"
CharmeleonFrontpic:  INCBIN "gfx/pokemon/charmeleon/front.animated.2bpp.lz"
KadabraFrontpic:     INCBIN "gfx/pokemon/kadabra/front.animated.2bpp.lz"
ExeggutorFrontpic:   INCBIN "gfx/pokemon/exeggutor/front.animated.2bpp.lz"
FantominusFrontpic:      INCBIN "gfx/pokemon/fantominus/front.animated.2bpp.lz"
AzumarillFrontpic:   INCBIN "gfx/pokemon/azumarill/front.animated.2bpp.lz"
ParasectFrontpic:    INCBIN "gfx/pokemon/parasect/front.animated.2bpp.lz"
MMimeFrontpic:      INCBIN "gfx/pokemon/m__mime/front.animated.2bpp.lz"
HeracrossFrontpic:   INCBIN "gfx/pokemon/heracross/front.animated.2bpp.lz"


SECTION "Pics 6", ROMX

AriadosFrontpic:     INCBIN "gfx/pokemon/ariados/front.animated.2bpp.lz"
NoctowlFrontpic:     INCBIN "gfx/pokemon/noctowl/front.animated.2bpp.lz"
CarabaffeFrontpic:   INCBIN "gfx/pokemon/carabaffe/front.animated.2bpp.lz"
LokhlassFrontpic:      INCBIN "gfx/pokemon/lokhlass/front.animated.2bpp.lz"
GrolemFrontpic:       INCBIN "gfx/pokemon/grolem/front.animated.2bpp.lz"
PoliwhirlFrontpic:   INCBIN "gfx/pokemon/poliwhirl/front.animated.2bpp.lz"
UrsaringFrontpic:    INCBIN "gfx/pokemon/ursaring/front.animated.2bpp.lz"
DemolosseFrontpic:    INCBIN "gfx/pokemon/demolosse/front.animated.2bpp.lz"
KabutopsFrontpic:    INCBIN "gfx/pokemon/kabutops/front.animated.2bpp.lz"
AmpharosFrontpic:    INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
NidorinaFrontpic:    INCBIN "gfx/pokemon/nidorina/front.animated.2bpp.lz"
FlareonFrontpic:     INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
CanartichoFrontpic:   INCBIN "gfx/pokemon/canarticho/front.animated.2bpp.lz"
VileplumeFrontpic:   INCBIN "gfx/pokemon/vileplume/front.animated.2bpp.lz"
MacroniumFrontpic:     INCBIN "gfx/pokemon/macronium/front.animated.2bpp.lz"
MagmarFrontpic:      INCBIN "gfx/pokemon/magmar/front.animated.2bpp.lz"
TentacruelFrontpic:  INCBIN "gfx/pokemon/tentacruel/front.animated.2bpp.lz"
ElekidFrontpic:      INCBIN "gfx/pokemon/elekid/front.animated.2bpp.lz"
CotovolFrontpic:    INCBIN "gfx/pokemon/cotovol/front.animated.2bpp.lz"
MarowakFrontpic:     INCBIN "gfx/pokemon/marowak/front.animated.2bpp.lz"
GoupixFrontpic:      INCBIN "gfx/pokemon/goupix/front.animated.2bpp.lz"
GligarFrontpic:      INCBIN "gfx/pokemon/gligar/front.animated.2bpp.lz"
InsolourdoFrontpic:   INCBIN "gfx/pokemon/insolourdo/front.animated.2bpp.lz"


SECTION "Pics 7", ROMX

AqualiFrontpic:    INCBIN "gfx/pokemon/aquali/front.animated.2bpp.lz"
GirafarigFrontpic:   INCBIN "gfx/pokemon/girafarig/front.animated.2bpp.lz"
DrowzeeFrontpic:     INCBIN "gfx/pokemon/drowzee/front.animated.2bpp.lz"
FarfuretFrontpic:     INCBIN "gfx/pokemon/farfuret/front.animated.2bpp.lz"
JoliflorFrontpic:   INCBIN "gfx/pokemon/joliflor/front.animated.2bpp.lz"
SnorlaxFrontpic:     INCBIN "gfx/pokemon/snorlax/front.animated.2bpp.lz"
GrodoudouFrontpic:  INCBIN "gfx/pokemon/grodoudou/front.animated.2bpp.lz"
YanmaFrontpic:       INCBIN "gfx/pokemon/yanma/front.animated.2bpp.lz"
SmeargleFrontpic:    INCBIN "gfx/pokemon/smeargle/front.animated.2bpp.lz"
ClefableFrontpic:    INCBIN "gfx/pokemon/clefable/front.animated.2bpp.lz"
PonytaFrontpic:      INCBIN "gfx/pokemon/ponyta/front.animated.2bpp.lz"
CornebreFrontpic:     INCBIN "gfx/pokemon/cornebre/front.animated.2bpp.lz"
GravalanchFrontpic:    INCBIN "gfx/pokemon/gravalanch/front.animated.2bpp.lz"
StarmieFrontpic:     INCBIN "gfx/pokemon/starmie/front.animated.2bpp.lz"
PidgeottoFrontpic:   INCBIN "gfx/pokemon/pidgeotto/front.animated.2bpp.lz"
CoxyFrontpic:      INCBIN "gfx/pokemon/coxy/front.animated.2bpp.lz"
EctoplasmaFrontpic:      INCBIN "gfx/pokemon/ectoplasma/front.animated.2bpp.lz"
AmonistarFrontpic:     INCBIN "gfx/pokemon/amonistar/front.animated.2bpp.lz"
CochignonFrontpic:   INCBIN "gfx/pokemon/cochignon/front.animated.2bpp.lz"
DugtrioFrontpic:     INCBIN "gfx/pokemon/dugtrio/front.animated.2bpp.lz"
MagnetonFrontpic:    INCBIN "gfx/pokemon/magneton/front.animated.2bpp.lz"
DracoFrontpic:   INCBIN "gfx/pokemon/draco/front.animated.2bpp.lz"
ForetressFrontpic:  INCBIN "gfx/pokemon/foretress/front.animated.2bpp.lz"
TogeticFrontpic:     INCBIN "gfx/pokemon/togetic/front.animated.2bpp.lz"
KangourexBackpic:   INCBIN "gfx/pokemon/kangourex/back.2bpp.lz"


SECTION "Pics 8", ROMX

SeelFrontpic:        INCBIN "gfx/pokemon/seel/front.animated.2bpp.lz"
CrobatFrontpic:      INCBIN "gfx/pokemon/crobat/front.animated.2bpp.lz"
LeveinardFrontpic:     INCBIN "gfx/pokemon/leveinard/front.animated.2bpp.lz"
TangelaFrontpic:     INCBIN "gfx/pokemon/tangela/front.animated.2bpp.lz"
SnubbullFrontpic:    INCBIN "gfx/pokemon/snubbull/front.animated.2bpp.lz"
GranbullFrontpic:    INCBIN "gfx/pokemon/granbull/front.animated.2bpp.lz"
EcremeuhFrontpic:     INCBIN "gfx/pokemon/ecremeuh/front.animated.2bpp.lz"
HaunterFrontpic:     INCBIN "gfx/pokemon/haunter/front.animated.2bpp.lz"
HeliatroncFrontpic:    INCBIN "gfx/pokemon/heliatronc/front.animated.2bpp.lz"
UmbreonFrontpic:     INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
GermignonFrontpic:   INCBIN "gfx/pokemon/germignon/front.animated.2bpp.lz"
GoldeenFrontpic:     INCBIN "gfx/pokemon/goldeen/front.animated.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
XatuFrontpic:        INCBIN "gfx/pokemon/xatu/front.animated.2bpp.lz"
MewFrontpic:         INCBIN "gfx/pokemon/mew/front.animated.2bpp.lz"
OctilleryFrontpic:   INCBIN "gfx/pokemon/octillery/front.animated.2bpp.lz"
LippoutouFrontpic:        INCBIN "gfx/pokemon/lippoutou/front.animated.2bpp.lz"
WobbuffetFrontpic:   INCBIN "gfx/pokemon/wobbuffet/front.animated.2bpp.lz"
CadoizoFrontpic:    INCBIN "gfx/pokemon/cadoizo/front.animated.2bpp.lz"
CoxyclaqueFrontpic:      INCBIN "gfx/pokemon/coxyclaque/front.animated.2bpp.lz"
GloomFrontpic:       INCBIN "gfx/pokemon/gloom/front.animated.2bpp.lz"
LainergieFrontpic:     INCBIN "gfx/pokemon/lainergie/front.animated.2bpp.lz"
HerbizarreFrontpic:     INCBIN "gfx/pokemon/herbizarre/front.animated.2bpp.lz"
FouinarFrontpic:      INCBIN "gfx/pokemon/fouinar/front.animated.2bpp.lz"
HericendreFrontpic:   INCBIN "gfx/pokemon/hericendre/front.animated.2bpp.lz"
HitmonchanFrontpic:  INCBIN "gfx/pokemon/hitmonchan/front.animated.2bpp.lz"
QuagsireFrontpic:    INCBIN "gfx/pokemon/quagsire/front.animated.2bpp.lz"


SECTION "Pics 9", ROMX

AboFrontpic:       INCBIN "gfx/pokemon/abo/front.animated.2bpp.lz"
SudowoodoFrontpic:   INCBIN "gfx/pokemon/sudowoodo/front.animated.2bpp.lz"
PikachuFrontpic:     INCBIN "gfx/pokemon/pikachu/front.animated.2bpp.lz"
HypoceanFrontpic:      INCBIN "gfx/pokemon/hypocean/front.animated.2bpp.lz"
MagbyFrontpic:       INCBIN "gfx/pokemon/magby/front.animated.2bpp.lz"
BoustiflorFrontpic:  INCBIN "gfx/pokemon/boustiflor/front.animated.2bpp.lz"
KaiminusFrontpic:    INCBIN "gfx/pokemon/kaiminus/front.animated.2bpp.lz"
CorayonFrontpic:     INCBIN "gfx/pokemon/corayon/front.animated.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
MachocFrontpic:      INCBIN "gfx/pokemon/machoc/front.animated.2bpp.lz"
LoupioFrontpic:    INCBIN "gfx/pokemon/loupio/front.animated.2bpp.lz"
RattataFrontpic:     INCBIN "gfx/pokemon/rattata/front.animated.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
SpearowFrontpic:     INCBIN "gfx/pokemon/spearow/front.animated.2bpp.lz"
MagikarpFrontpic:    INCBIN "gfx/pokemon/magikarp/front.animated.2bpp.lz"
CharmanderFrontpic:  INCBIN "gfx/pokemon/charmander/front.animated.2bpp.lz"
CuboneFrontpic:      INCBIN "gfx/pokemon/cubone/front.animated.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
NidoranMFrontpic:    INCBIN "gfx/pokemon/nidoran_m/front.animated.2bpp.lz"
PorygonFrontpic:     INCBIN "gfx/pokemon/porygon/front.animated.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
GrimerFrontpic:      INCBIN "gfx/pokemon/grimer/front.animated.2bpp.lz"
StaryuFrontpic:      INCBIN "gfx/pokemon/staryu/front.animated.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
MeowthFrontpic:      INCBIN "gfx/pokemon/meowth/front.animated.2bpp.lz"
Porygon2Frontpic:    INCBIN "gfx/pokemon/porygon2/front.animated.2bpp.lz"
SandshrewFrontpic:   INCBIN "gfx/pokemon/sandshrew/front.animated.2bpp.lz"
NidoranFFrontpic:    INCBIN "gfx/pokemon/nidoran_f/front.animated.2bpp.lz"
PidgeyFrontpic:      INCBIN "gfx/pokemon/pidgey/front.animated.2bpp.lz"
ParasectBackpic:     INCBIN "gfx/pokemon/parasect/back.2bpp.lz"


SECTION "Pics 10", ROMX

FeuforeveFrontpic:  INCBIN "gfx/pokemon/feuforeve/front.animated.2bpp.lz"
HoundourFrontpic:    INCBIN "gfx/pokemon/houndour/front.animated.2bpp.lz"
FerosingeFrontpic:      INCBIN "gfx/pokemon/ferosinge/front.animated.2bpp.lz"
CelebiFrontpic:      INCBIN "gfx/pokemon/celebi/front.animated.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
PinecoFrontpic:      INCBIN "gfx/pokemon/pineco/front.animated.2bpp.lz"
KrabbyFrontpic:      INCBIN "gfx/pokemon/krabby/front.animated.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
JigglypuffFrontpic:  INCBIN "gfx/pokemon/jigglypuff/front.animated.2bpp.lz"
ParasFrontpic:       INCBIN "gfx/pokemon/paras/front.animated.2bpp.lz"
NidokingBackpic:     INCBIN "gfx/pokemon/nidoking/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
PsyduckFrontpic:     INCBIN "gfx/pokemon/psyduck/front.animated.2bpp.lz"
CarapuceFrontpic:    INCBIN "gfx/pokemon/carapuce/front.animated.2bpp.lz"
MackogneurBackpic:      INCBIN "gfx/pokemon/mackogneur/back.2bpp.lz"
KoffingFrontpic:     INCBIN "gfx/pokemon/koffing/front.animated.2bpp.lz"
VenonatFrontpic:     INCBIN "gfx/pokemon/venonat/front.animated.2bpp.lz"
ExeggutorBackpic:    INCBIN "gfx/pokemon/exeggutor/back.2bpp.lz"
LanturnFrontpic:     INCBIN "gfx/pokemon/lanturn/front.animated.2bpp.lz"
DebugantFrontpic:     INCBIN "gfx/pokemon/debugant/front.animated.2bpp.lz"
FloravolFrontpic:    INCBIN "gfx/pokemon/floravol/front.animated.2bpp.lz"
MareepFrontpic:      INCBIN "gfx/pokemon/mareep/front.animated.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/chuck.2bpp.lz"
EvoliFrontpic:       INCBIN "gfx/pokemon/evoli/front.animated.2bpp.lz"
ButterfreeBackpic:   INCBIN "gfx/pokemon/butterfree/back.2bpp.lz"
ZubatFrontpic:       INCBIN "gfx/pokemon/zubat/front.animated.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
AlakazamBackpic:     INCBIN "gfx/pokemon/alakazam/back.2bpp.lz"
CapumainFrontpic:       INCBIN "gfx/pokemon/capumain/front.animated.2bpp.lz"
AbraFrontpic:        INCBIN "gfx/pokemon/abra/front.animated.2bpp.lz"
KapoeraBackpic:    INCBIN "gfx/pokemon/kapoera/back.2bpp.lz"
CrustabriBackpic:     INCBIN "gfx/pokemon/crustabri/back.2bpp.lz"
HoothootFrontpic:    INCBIN "gfx/pokemon/hoothoot/front.animated.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"


SECTION "Pics 11", ROMX

DodrioBackpic:       INCBIN "gfx/pokemon/dodrio/back.2bpp.lz"
ClefairyFrontpic:    INCBIN "gfx/pokemon/clefairy/front.animated.2bpp.lz"
LimagmaFrontpic:      INCBIN "gfx/pokemon/limagma/front.animated.2bpp.lz"
CaninosFrontpic:   INCBIN "gfx/pokemon/caninos/front.animated.2bpp.lz"
SlowpokeFrontpic:    INCBIN "gfx/pokemon/slowpoke/front.animated.2bpp.lz"
LippoutiFrontpic:    INCBIN "gfx/pokemon/lippouti/front.animated.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
MarillFrontpic:      INCBIN "gfx/pokemon/marill/front.animated.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
AeromiteBackpic:     INCBIN "gfx/pokemon/aeromite/back.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/clair.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
AmonitaFrontpic:     INCBIN "gfx/pokemon/amonita/front.animated.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
PupitarFrontpic:     INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
ChetiflorFrontpic:  INCBIN "gfx/pokemon/chetiflor/front.animated.2bpp.lz"
KokiyasFrontpic:    INCBIN "gfx/pokemon/kokiyas/front.animated.2bpp.lz"
TentacoolFrontpic:   INCBIN "gfx/pokemon/tentacool/front.animated.2bpp.lz"
CleffaFrontpic:      INCBIN "gfx/pokemon/cleffa/front.animated.2bpp.lz"
LeviatorBackpic:     INCBIN "gfx/pokemon/leviator/back.2bpp.lz"
FeunardBackpic:    INCBIN "gfx/pokemon/feunard/back.2bpp.lz"
YanmaBackpic:        INCBIN "gfx/pokemon/yanma/back.2bpp.lz"
PinsirBackpic:       INCBIN "gfx/pokemon/pinsir/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
ClefableBackpic:     INCBIN "gfx/pokemon/clefable/back.2bpp.lz"
DoduoFrontpic:       INCBIN "gfx/pokemon/doduo/front.animated.2bpp.lz"
AligatueurBackpic:   INCBIN "gfx/pokemon/aligatueur/back.2bpp.lz"
DratiniFrontpic:     INCBIN "gfx/pokemon/dratini/front.animated.2bpp.lz"
MagnetonBackpic:     INCBIN "gfx/pokemon/magneton/back.2bpp.lz"
QwilfishFrontpic:    INCBIN "gfx/pokemon/qwilfish/front.animated.2bpp.lz"
SuicuneBackpic:      INCBIN "gfx/pokemon/suicune/back.2bpp.lz"
SlowkingBackpic:     INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
ElekidBackpic:       INCBIN "gfx/pokemon/elekid/back.2bpp.lz"
CelebiBackpic:       INCBIN "gfx/pokemon/celebi/back.2bpp.lz"
KrabbyBackpic:       INCBIN "gfx/pokemon/krabby/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
SnorlaxBackpic:      INCBIN "gfx/pokemon/snorlax/back.2bpp.lz"


SECTION "Pics 12", ROMX

FlorizarreBackpic:     INCBIN "gfx/pokemon/florizarre/back.2bpp.lz"
MoltresBackpic:      INCBIN "gfx/pokemon/moltres/back.2bpp.lz"
HeliatroncBackpic:     INCBIN "gfx/pokemon/heliatronc/back.2bpp.lz"
PhanpyFrontpic:      INCBIN "gfx/pokemon/phanpy/front.animated.2bpp.lz"
RhydonBackpic:       INCBIN "gfx/pokemon/rhydon/back.2bpp.lz"
EmbrylexFrontpic:    INCBIN "gfx/pokemon/embrylex/front.animated.2bpp.lz"
TyranitarBackpic:    INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
SandslashBackpic:    INCBIN "gfx/pokemon/sandslash/back.2bpp.lz"
HypoceanBackpic:       INCBIN "gfx/pokemon/hypocean/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
CanartichoBackpic:    INCBIN "gfx/pokemon/canarticho/back.2bpp.lz"
NidoranMBackpic:     INCBIN "gfx/pokemon/nidoran_m/back.2bpp.lz"
CoxyBackpic:       INCBIN "gfx/pokemon/coxy/back.2bpp.lz"
HericendreBackpic:    INCBIN "gfx/pokemon/hericendre/back.2bpp.lz"
MacroniumBackpic:      INCBIN "gfx/pokemon/macronium/back.2bpp.lz"
OddishFrontpic:      INCBIN "gfx/pokemon/oddish/front.animated.2bpp.lz"
GalopaBackpic:     INCBIN "gfx/pokemon/galopa/back.2bpp.lz"
DoduoBackpic:        INCBIN "gfx/pokemon/doduo/back.2bpp.lz"
GranivolFrontpic:      INCBIN "gfx/pokemon/granivol/front.animated.2bpp.lz"
FerosingeBackpic:       INCBIN "gfx/pokemon/ferosinge/back.2bpp.lz"
MagmarBackpic:       INCBIN "gfx/pokemon/magmar/back.2bpp.lz"
HypnomadeBackpic:        INCBIN "gfx/pokemon/hypnomade/back.2bpp.lz"
FeurissonBackpic:      INCBIN "gfx/pokemon/feurisson/back.2bpp.lz"
CrocrodilBackpic:     INCBIN "gfx/pokemon/crocrodil/back.2bpp.lz"
SandshrewBackpic:    INCBIN "gfx/pokemon/sandshrew/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
KokiyasBackpic:     INCBIN "gfx/pokemon/kokiyas/back.2bpp.lz"
ZubatBackpic:        INCBIN "gfx/pokemon/zubat/back.2bpp.lz"
TeddiursaFrontpic:   INCBIN "gfx/pokemon/teddiursa/front.animated.2bpp.lz"
CuboneBackpic:       INCBIN "gfx/pokemon/cubone/back.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"
GloomBackpic:        INCBIN "gfx/pokemon/gloom/back.2bpp.lz"
MagcargoBackpic:     INCBIN "gfx/pokemon/magcargo/back.2bpp.lz"
KabutopsBackpic:     INCBIN "gfx/pokemon/kabutops/back.2bpp.lz"
DardargnanBackpic:     INCBIN "gfx/pokemon/dardargnan/back.2bpp.lz"
ArcaninBackpic:     INCBIN "gfx/pokemon/arcanin/back.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
GoldeenBackpic:      INCBIN "gfx/pokemon/goldeen/back.2bpp.lz"
BulbizarreFrontpic:   INCBIN "gfx/pokemon/bulbizarre/front.animated.2bpp.lz"
StarmieBackpic:      INCBIN "gfx/pokemon/starmie/back.2bpp.lz"


SECTION "Pics 13", ROMX

AmonitaBackpic:      INCBIN "gfx/pokemon/amonita/back.2bpp.lz"
PidgeyBackpic:       INCBIN "gfx/pokemon/pidgey/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
QwilfishBackpic:     INCBIN "gfx/pokemon/qwilfish/back.2bpp.lz"
GligarBackpic:       INCBIN "gfx/pokemon/gligar/back.2bpp.lz"
TyphlosionBackpic:   INCBIN "gfx/pokemon/typhlosion/back.2bpp.lz"
CharmeleonBackpic:   INCBIN "gfx/pokemon/charmeleon/back.2bpp.lz"
NidoqueenBackpic:    INCBIN "gfx/pokemon/nidoqueen/back.2bpp.lz"
PichuFrontpic:       INCBIN "gfx/pokemon/pichu/front.animated.2bpp.lz"
ElektekBackpic:   INCBIN "gfx/pokemon/elektek/back.2bpp.lz"
CoxyclaqueBackpic:       INCBIN "gfx/pokemon/coxyclaque/back.2bpp.lz"
PupitarBackpic:      INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
HeracrossBackpic:    INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
EcremeuhBackpic:      INCBIN "gfx/pokemon/ecremeuh/back.2bpp.lz"
SteelixBackpic:      INCBIN "gfx/pokemon/steelix/back.2bpp.lz"
PersianBackpic:      INCBIN "gfx/pokemon/persian/back.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
EvoliBackpic:        INCBIN "gfx/pokemon/evoli/back.2bpp.lz"
CaratrocFrontpic:     INCBIN "gfx/pokemon/caratroc/front.animated.2bpp.lz"
PonytaBackpic:       INCBIN "gfx/pokemon/ponyta/back.2bpp.lz"
RemoraidFrontpic:    INCBIN "gfx/pokemon/remoraid/front.animated.2bpp.lz"
PoliwagFrontpic:     INCBIN "gfx/pokemon/poliwag/front.animated.2bpp.lz"
OnixBackpic:         INCBIN "gfx/pokemon/onix/back.2bpp.lz"
KoffingBackpic:      INCBIN "gfx/pokemon/koffing/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
KarenPic:            INCBIN "gfx/trainers/karen.2bpp.lz"
NidorinaBackpic:     INCBIN "gfx/pokemon/nidorina/back.2bpp.lz"
TentacruelBackpic:   INCBIN "gfx/pokemon/tentacruel/back.2bpp.lz"
CaninosBackpic:    INCBIN "gfx/pokemon/caninos/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
MachopeurBackpic:      INCBIN "gfx/pokemon/machopeur/back.2bpp.lz"
RaichuBackpic:       INCBIN "gfx/pokemon/raichu/back.2bpp.lz"
PoliwrathBackpic:    INCBIN "gfx/pokemon/poliwrath/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
SunkernFrontpic:     INCBIN "gfx/pokemon/sunkern/front.animated.2bpp.lz"
NidorinoBackpic:     INCBIN "gfx/pokemon/nidorino/back.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
ElectrodeFrontpic:   INCBIN "gfx/pokemon/electrode/front.animated.2bpp.lz"


SECTION "Pics 14", ROMX

SudowoodoBackpic:    INCBIN "gfx/pokemon/sudowoodo/back.2bpp.lz"
LainergieBackpic:      INCBIN "gfx/pokemon/lainergie/back.2bpp.lz"
FouinetteFrontpic:     INCBIN "gfx/pokemon/fouinette/front.animated.2bpp.lz"
TogeticBackpic:      INCBIN "gfx/pokemon/togetic/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
MarowakBackpic:      INCBIN "gfx/pokemon/marowak/back.2bpp.lz"
GeodudeBackpic:      INCBIN "gfx/pokemon/geodude/back.2bpp.lz"
InsecateurBackpic:      INCBIN "gfx/pokemon/insecateur/back.2bpp.lz"
VileplumeBackpic:    INCBIN "gfx/pokemon/vileplume/back.2bpp.lz"
HitmonchanBackpic:   INCBIN "gfx/pokemon/hitmonchan/back.2bpp.lz"
CotovolBackpic:     INCBIN "gfx/pokemon/cotovol/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
BlastoiseBackpic:    INCBIN "gfx/pokemon/blastoise/back.2bpp.lz"
FeuforeveBackpic:   INCBIN "gfx/pokemon/feuforeve/back.2bpp.lz"
DebugantBackpic:      INCBIN "gfx/pokemon/debugant/back.2bpp.lz"
GeodudeFrontpic:     INCBIN "gfx/pokemon/geodude/front.animated.2bpp.lz"
CizayoxBackpic:       INCBIN "gfx/pokemon/cizayox/back.2bpp.lz"
GirafarigBackpic:    INCBIN "gfx/pokemon/girafarig/back.2bpp.lz"
CerfrousseBackpic:     INCBIN "gfx/pokemon/cerfrousse/back.2bpp.lz"
SmeargleBackpic:     INCBIN "gfx/pokemon/smeargle/back.2bpp.lz"
DracaufeuBackpic:    INCBIN "gfx/pokemon/dracaufeu/back.2bpp.lz"
KadabraBackpic:      INCBIN "gfx/pokemon/kadabra/back.2bpp.lz"
ColossingeBackpic:     INCBIN "gfx/pokemon/colossinge/back.2bpp.lz"
FouinarBackpic:       INCBIN "gfx/pokemon/fouinar/back.2bpp.lz"
CarabaffeBackpic:    INCBIN "gfx/pokemon/carabaffe/back.2bpp.lz"
ExeggcuteBackpic:    INCBIN "gfx/pokemon/exeggcute/back.2bpp.lz"
IgglybuffFrontpic:   INCBIN "gfx/pokemon/igglybuff/front.animated.2bpp.lz"
RaticateBackpic:     INCBIN "gfx/pokemon/raticate/back.2bpp.lz"
GoupixBackpic:       INCBIN "gfx/pokemon/goupix/back.2bpp.lz"
AboBackpic:        INCBIN "gfx/pokemon/abo/back.2bpp.lz"
SeakingBackpic:      INCBIN "gfx/pokemon/seaking/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
PsyduckBackpic:      INCBIN "gfx/pokemon/psyduck/back.2bpp.lz"
PikachuBackpic:      INCBIN "gfx/pokemon/pikachu/back.2bpp.lz"
KabutoFrontpic:      INCBIN "gfx/pokemon/kabuto/front.animated.2bpp.lz"
MareepBackpic:       INCBIN "gfx/pokemon/mareep/back.2bpp.lz"
RemoraidBackpic:     INCBIN "gfx/pokemon/remoraid/back.2bpp.lz"
DittoFrontpic:       INCBIN "gfx/pokemon/ditto/front.animated.2bpp.lz"
HyporoiBackpic:      INCBIN "gfx/pokemon/hyporoi/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
AxolotoFrontpic:      INCBIN "gfx/pokemon/axoloto/front.animated.2bpp.lz"
ClefairyBackpic:     INCBIN "gfx/pokemon/clefairy/back.2bpp.lz"
VenonatBackpic:      INCBIN "gfx/pokemon/venonat/back.2bpp.lz"
JoliflorBackpic:    INCBIN "gfx/pokemon/joliflor/back.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
SwinubBackpic:       INCBIN "gfx/pokemon/swinub/back.2bpp.lz"


SECTION "Pics 15", ROMX

MewtwoBackpic:       INCBIN "gfx/pokemon/mewtwo/back.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/oak.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
DiglettFrontpic:     INCBIN "gfx/pokemon/diglett/front.animated.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
GrotadmorvBackpic:          INCBIN "gfx/pokemon/grotadmorv/back.2bpp.lz"
CadoizoBackpic:     INCBIN "gfx/pokemon/cadoizo/back.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
MagikarpBackpic:     INCBIN "gfx/pokemon/magikarp/back.2bpp.lz"
AriadosBackpic:      INCBIN "gfx/pokemon/ariados/back.2bpp.lz"
FarfuretBackpic:      INCBIN "gfx/pokemon/farfuret/back.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
CornebreBackpic:      INCBIN "gfx/pokemon/cornebre/back.2bpp.lz"
HerbizarreBackpic:      INCBIN "gfx/pokemon/herbizarre/back.2bpp.lz"
FlagadossBackpic:      INCBIN "gfx/pokemon/flagadoss/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
AkwakwakBackpic:      INCBIN "gfx/pokemon/akwakwak/back.2bpp.lz"
WeezingBackpic:      INCBIN "gfx/pokemon/weezing/back.2bpp.lz"
EnteiBackpic:        INCBIN "gfx/pokemon/entei/back.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/grunt_f.2bpp.lz"
HypotrempeFrontpic:      INCBIN "gfx/pokemon/hypotrempe/front.animated.2bpp.lz"
PidgeotBackpic:      INCBIN "gfx/pokemon/pidgeot/back.2bpp.lz"
HoOhBackpic:         INCBIN "gfx/pokemon/ho_oh/back.2bpp.lz"
PoliwhirlBackpic:    INCBIN "gfx/pokemon/poliwhirl/back.2bpp.lz"
MewBackpic:          INCBIN "gfx/pokemon/mew/back.2bpp.lz"
MachocBackpic:       INCBIN "gfx/pokemon/machoc/back.2bpp.lz"
AbraBackpic:         INCBIN "gfx/pokemon/abra/back.2bpp.lz"
AerodactylBackpic:   INCBIN "gfx/pokemon/aerodactyl/back.2bpp.lz"
CoconfortFrontpic:      INCBIN "gfx/pokemon/coconfort/front.animated.2bpp.lz"
DugtrioBackpic:      INCBIN "gfx/pokemon/dugtrio/back.2bpp.lz"
BoustiflorBackpic:   INCBIN "gfx/pokemon/boustiflor/back.2bpp.lz"
NidoranFBackpic:     INCBIN "gfx/pokemon/nidoran_f/back.2bpp.lz"
GravalanchBackpic:     INCBIN "gfx/pokemon/gravalanch/back.2bpp.lz"
CapumainBackpic:        INCBIN "gfx/pokemon/capumain/back.2bpp.lz"
EspeonBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
AspicotFrontpic:      INCBIN "gfx/pokemon/aspicot/front.animated.2bpp.lz"
KaiminusBackpic:     INCBIN "gfx/pokemon/kaiminus/back.2bpp.lz"
SnubbullBackpic:     INCBIN "gfx/pokemon/snubbull/back.2bpp.lz"
KrabbossBackpic:      INCBIN "gfx/pokemon/krabboss/back.2bpp.lz"
EctoplasmaBackpic:       INCBIN "gfx/pokemon/ectoplasma/back.2bpp.lz"
RattataBackpic:      INCBIN "gfx/pokemon/rattata/back.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
WillPic:             INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
MagnemiteFrontpic:   INCBIN "gfx/pokemon/magnemite/front.animated.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
MagnemiteBackpic:    INCBIN "gfx/pokemon/magnemite/back.2bpp.lz"


SECTION "Pics 16", ROMX

HoothootBackpic:     INCBIN "gfx/pokemon/hoothoot/back.2bpp.lz"
NoctowlBackpic:      INCBIN "gfx/pokemon/noctowl/back.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/morty.2bpp.lz"
LimagmaBackpic:       INCBIN "gfx/pokemon/limagma/back.2bpp.lz"
KabutoBackpic:       INCBIN "gfx/pokemon/kabuto/back.2bpp.lz"
EmpiflorBackpic:   INCBIN "gfx/pokemon/empiflor/back.2bpp.lz"
MeowthBackpic:       INCBIN "gfx/pokemon/meowth/back.2bpp.lz"
MeganiumBackpic:     INCBIN "gfx/pokemon/meganium/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
ExcelangueBackpic:    INCBIN "gfx/pokemon/excelangue/back.2bpp.lz"
TogepiFrontpic:      INCBIN "gfx/pokemon/togepi/front.animated.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
HaunterBackpic:      INCBIN "gfx/pokemon/haunter/back.2bpp.lz"
XatuBackpic:         INCBIN "gfx/pokemon/xatu/back.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
Porygon2Backpic:     INCBIN "gfx/pokemon/porygon2/back.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/jasmine.2bpp.lz"
PinecoBackpic:       INCBIN "gfx/pokemon/pineco/back.2bpp.lz"
ChrysacierFrontpic:     INCBIN "gfx/pokemon/chrysacier/front.animated.2bpp.lz"
SeelBackpic:         INCBIN "gfx/pokemon/seel/back.2bpp.lz"
QuagsireBackpic:     INCBIN "gfx/pokemon/quagsire/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
JolteonBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
ChenipanFrontpic:    INCBIN "gfx/pokemon/chenipan/front.animated.2bpp.lz"
GranivolBackpic:       INCBIN "gfx/pokemon/granivol/back.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
GranbullBackpic:     INCBIN "gfx/pokemon/granbull/back.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
SpearowBackpic:      INCBIN "gfx/pokemon/spearow/back.2bpp.lz"
SunkernBackpic:      INCBIN "gfx/pokemon/sunkern/back.2bpp.lz"
LokhlassBackpic:       INCBIN "gfx/pokemon/lokhlass/back.2bpp.lz"
MagbyBackpic:        INCBIN "gfx/pokemon/magby/back.2bpp.lz"
DracoBackpic:    INCBIN "gfx/pokemon/draco/back.2bpp.lz"
ElecthorBackpic:       INCBIN "gfx/pokemon/electhor/back.2bpp.lz"
GermignonBackpic:    INCBIN "gfx/pokemon/germignon/back.2bpp.lz"
CorayonBackpic:      INCBIN "gfx/pokemon/corayon/back.2bpp.lz"
LoupioBackpic:     INCBIN "gfx/pokemon/loupio/back.2bpp.lz"
LeveinardBackpic:      INCBIN "gfx/pokemon/leveinard/back.2bpp.lz"
FloravolBackpic:     INCBIN "gfx/pokemon/floravol/back.2bpp.lz"
SpinarakFrontpic:    INCBIN "gfx/pokemon/spinarak/front.animated.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
CharmanderBackpic:   INCBIN "gfx/pokemon/charmander/back.2bpp.lz"
RhyhornBackpic:      INCBIN "gfx/pokemon/rhyhorn/back.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
SwinubFrontpic:      INCBIN "gfx/pokemon/swinub/front.animated.2bpp.lz"
EmbrylexBackpic:     INCBIN "gfx/pokemon/embrylex/back.2bpp.lz"
PorygonBackpic:      INCBIN "gfx/pokemon/porygon/back.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"


SECTION "Pics 17", ROMX

ParasBackpic:        INCBIN "gfx/pokemon/paras/back.2bpp.lz"
AqualiBackpic:     INCBIN "gfx/pokemon/aquali/back.2bpp.lz"
TentacoolBackpic:    INCBIN "gfx/pokemon/tentacool/back.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
BulbizarreBackpic:    INCBIN "gfx/pokemon/bulbizarre/back.2bpp.lz"
LippoutiBackpic:     INCBIN "gfx/pokemon/lippouti/back.2bpp.lz"
PichuBackpic:        INCBIN "gfx/pokemon/pichu/back.2bpp.lz"
DemolosseBackpic:     INCBIN "gfx/pokemon/demolosse/back.2bpp.lz"
ChetiflorBackpic:   INCBIN "gfx/pokemon/chetiflor/back.2bpp.lz"
GrimerBackpic:       INCBIN "gfx/pokemon/grimer/back.2bpp.lz"
LanturnBackpic:      INCBIN "gfx/pokemon/lanturn/back.2bpp.lz"
PidgeottoBackpic:    INCBIN "gfx/pokemon/pidgeotto/back.2bpp.lz"
StaryuBackpic:       INCBIN "gfx/pokemon/staryu/back.2bpp.lz"
MMimeBackpic:       INCBIN "gfx/pokemon/m__mime/back.2bpp.lz"
ChenipanBackpic:     INCBIN "gfx/pokemon/chenipan/back.2bpp.lz"
VoltorbFrontpic:     INCBIN "gfx/pokemon/voltorb/front.animated.2bpp.lz"
LugiaBackpic:        INCBIN "gfx/pokemon/lugia/back.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/pryce.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
ArbokBackpic:        INCBIN "gfx/pokemon/arbok/back.2bpp.lz"
PolitoedBackpic:     INCBIN "gfx/pokemon/politoed/back.2bpp.lz"
DracolosseBackpic:    INCBIN "gfx/pokemon/dracolosse/back.2bpp.lz"
KickleeBackpic:    INCBIN "gfx/pokemon/kicklee/back.2bpp.lz"
NatuFrontpic:        INCBIN "gfx/pokemon/natu/front.animated.2bpp.lz"
UrsaringBackpic:     INCBIN "gfx/pokemon/ursaring/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
TeddiursaBackpic:    INCBIN "gfx/pokemon/teddiursa/back.2bpp.lz"
PhanpyBackpic:       INCBIN "gfx/pokemon/phanpy/back.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
CoconfortBackpic:       INCBIN "gfx/pokemon/coconfort/back.2bpp.lz"
WobbuffetBackpic:    INCBIN "gfx/pokemon/wobbuffet/back.2bpp.lz"
TogepiBackpic:       INCBIN "gfx/pokemon/togepi/back.2bpp.lz"
CrobatBackpic:       INCBIN "gfx/pokemon/crobat/back.2bpp.lz"
LeuphorieBackpic:      INCBIN "gfx/pokemon/leuphorie/back.2bpp.lz"
AmpharosBackpic:     INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
IgglybuffBackpic:    INCBIN "gfx/pokemon/igglybuff/back.2bpp.lz"
AzumarillBackpic:    INCBIN "gfx/pokemon/azumarill/back.2bpp.lz"
OctilleryBackpic:    INCBIN "gfx/pokemon/octillery/back.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
HypotrempeBackpic:       INCBIN "gfx/pokemon/hypotrempe/back.2bpp.lz"
FouinetteBackpic:      INCBIN "gfx/pokemon/fouinette/back.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
GrodoudouBackpic:   INCBIN "gfx/pokemon/grodoudou/back.2bpp.lz"
ArtikodinBackpic:     INCBIN "gfx/pokemon/artikodin/back.2bpp.lz"
DittoBackpic:        INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
AspicotBackpic:       INCBIN "gfx/pokemon/aspicot/back.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"
CleffaBackpic:       INCBIN "gfx/pokemon/cleffa/back.2bpp.lz"
DrowzeeBackpic:      INCBIN "gfx/pokemon/drowzee/back.2bpp.lz"
FantominusBackpic:       INCBIN "gfx/pokemon/fantominus/back.2bpp.lz"
FearowBackpic:       INCBIN "gfx/pokemon/fearow/back.2bpp.lz"
MarillBackpic:       INCBIN "gfx/pokemon/marill/back.2bpp.lz"
DratiniBackpic:      INCBIN "gfx/pokemon/dratini/back.2bpp.lz"
ElectrodeBackpic:    INCBIN "gfx/pokemon/electrode/back.2bpp.lz"
AirmureBackpic:     INCBIN "gfx/pokemon/airmure/back.2bpp.lz"
ChrysacierBackpic:      INCBIN "gfx/pokemon/chrysacier/back.2bpp.lz"
JigglypuffBackpic:   INCBIN "gfx/pokemon/jigglypuff/back.2bpp.lz"
OddishBackpic:       INCBIN "gfx/pokemon/oddish/back.2bpp.lz"
UnownDBackpic:       INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"


SECTION "Pics 18", ROMX

SpinarakBackpic:     INCBIN "gfx/pokemon/spinarak/back.2bpp.lz"
RaikouBackpic:       INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
HoundourBackpic:     INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
PoliwagBackpic:      INCBIN "gfx/pokemon/poliwag/back.2bpp.lz"
CarapuceBackpic:     INCBIN "gfx/pokemon/carapuce/back.2bpp.lz"
CaratrocBackpic:      INCBIN "gfx/pokemon/caratroc/back.2bpp.lz"
LamantineBackpic:      INCBIN "gfx/pokemon/lamantine/back.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
SlowpokeBackpic:     INCBIN "gfx/pokemon/slowpoke/back.2bpp.lz"
InsolourdoBackpic:    INCBIN "gfx/pokemon/insolourdo/back.2bpp.lz"
DonphanBackpic:      INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
AxolotoBackpic:       INCBIN "gfx/pokemon/axoloto/back.2bpp.lz"
TaurosBackpic:       INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
TangelaBackpic:      INCBIN "gfx/pokemon/tangela/back.2bpp.lz"
VoltorbBackpic:      INCBIN "gfx/pokemon/voltorb/back.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
DemantaBackpic:      INCBIN "gfx/pokemon/demanta/back.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
CochignonBackpic:    INCBIN "gfx/pokemon/cochignon/back.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
NatuBackpic:         INCBIN "gfx/pokemon/natu/back.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
GrolemBackpic:        INCBIN "gfx/pokemon/grolem/back.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
DiglettBackpic:      INCBIN "gfx/pokemon/diglett/back.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
LippoutouBackpic:         INCBIN "gfx/pokemon/lippoutou/back.2bpp.lz"
GolbatBackpic:       INCBIN "gfx/pokemon/golbat/back.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
ForetressBackpic:   INCBIN "gfx/pokemon/foretress/back.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownIBackpic:       INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownRBackpic:       INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"


SECTION "Pics 19", ROMX

; Seems to be an accidental copy of the previous bank

INCBIN "gfx/pokemon/spinarak/back.2bpp.lz"
INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
INCBIN "gfx/pokemon/poliwag/back.2bpp.lz"
INCBIN "gfx/pokemon/carapuce/back.2bpp.lz"
INCBIN "gfx/pokemon/caratroc/back.2bpp.lz"
INCBIN "gfx/pokemon/lamantine/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/slowpoke/back.2bpp.lz"
INCBIN "gfx/pokemon/insolourdo/back.2bpp.lz"
INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
INCBIN "gfx/pokemon/axoloto/back.2bpp.lz"
INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/tangela/back.2bpp.lz"
INCBIN "gfx/pokemon/voltorb/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/demanta/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/cochignon/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/natu/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/grolem/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/diglett/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
INCBIN "gfx/pokemon/lippoutou/back.2bpp.lz"
INCBIN "gfx/pokemon/golbat/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
INCBIN "gfx/pokemon/foretress/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"


; Sections "Pics 20" to "Pics 24" are not used for any graphics,
; but entries for their banks exist in FixPicBank (see engine/gfx/load_pics.asm).

SECTION "Pics 20", ROMX

SECTION "Pics 21", ROMX

SECTION "Pics 22", ROMX

SECTION "Pics 23", ROMX

SECTION "Pics 24", ROMX
